let shopItemsData = [
  {
    id: "abcd",
    name: "Choco Muffin",
    price: 1,
    desc: "Delicious chocolate muffin, perfect for a sweet treat.",
    category: "Muffin",
    img: ".././Images/Products/1.png",
  },
  {
    id: "xyzh",
    name: "Lava Bread",
    price: 2,
    desc: "A delightful bread with a lava-like texture inside.",
    category: "Bread",
    img: ".././Images/Products/2.png",
  },
  {
    id: "ujfh",
    name: "French Bread",
    price: 1,
    desc: "Classic French bread, crispy on the outside and soft inside.",
    category: "Bread",
    img: ".././Images/Products/3.png",
  },
  {
    id: "oqis",
    name: "Berry Sandwich Loaf",
    price: 4,
    desc: "A loaf filled with a burst of berry flavors in every slice.",
    category: "Bread",
    img: ".././Images/Products/4.png",
  },
  {
    id: "mdns",
    name: "Butter Cheese Bread",
    price: 6,
    desc: "Rich in buttery and cheesy goodness, a bread-lover's delight.",
    category: "Bread",
    img: ".././Images/Products/5.png",
  },
  {
    id: "qweo",
    name: "Cheese Cake",
    price: 6,
    desc: "Indulge in a creamy cheesecake that melts in your mouth.",
    category: "Cake",
    img: ".././Images/Products/6.png",
  },
  {
    id: "gnms",
    name: "Brown Sugar Bread",
    price: 5.2,
    desc: "Savor the sweetness of brown sugar in every bite.",
    category: "Bread",
    img: ".././Images/Products/7.png",
  },
  {
    id: "qwuh",
    name: "Cream Cake",
    price: 1,
    desc: "A light and fluffy cake topped with creamy goodness.",
    category: "Cake",
    img: ".././Images/Products/8.png",
  },
  {
    id: "ibch",
    name: "Almond Bread Loaf",
    price: 5,
    desc: "A nutty delight featuring the richness of almonds.",
    category: "Bread",
    img: ".././Images/Products/9.png",
  },
  {
    id: "jjjm",
    name: "Butter Cake",
    price: 4,
    desc: "Experience the buttery richness of this classic cake.",
    category: "Cake",
    img: ".././Images/Products/10.png",
  },
  {
    id: "kisjf",
    name: "Honey Pancake",
    price: 2,
    desc: "Enjoy fluffy pancakes drizzled with sweet honey.",
    category: "Cake",
    img: ".././Images/Products/11.png",
  },
  {
    id: "qqwu",
    name: "Berry Muffin",
    price: 3,
    desc: "A burst of berry flavors in a delightful muffin.",
    category: "Muffin",
    img: ".././Images/Products/12.png",
  },
  {
    id: "msad",
    name: "Croissant",
    price: 4,
    desc: "Savor the flaky layers of a classic croissant.",
    category: "Bread",
    img: ".././Images/Products/13.png",
  },
  {
    id: "oran",
    name: "Florence Oval",
    price: 3,
    desc: "A unique oval-shaped bread, perfect for any occasion.",
    category: "Bread",
    img: ".././Images/Products/14.png",
  },
  {
    id: "psdaj",
    name: "Original Cookie",
    price: 2,
    desc: "Classic cookie goodness that delights with every bite",
    category: "Bread",
    img: ".././Images/Products/15.png",
  },
  {
    id: "proSB",
    name: "Snow Bagel",
    price: 3,
    desc: "A bagel that brings a snowfall of flavors to your palate.",
    category: "Bread",
    img: ".././Images/Products/16.png",
  },

];

