let shopItemsData = [
  {
    id: "abcd",
    name: "Choco Muffin",
    price: 1.2,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Muffin",
    img: "images/img-1.jpg",
  },
  {
    id: "xyzh",
    name: "Lava Bread",
    price: 2.5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "images/img-2.jpg",
  },
  {
    id: "ujfh",
    name: "French Bread",
    price: 1.25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Cookies",
    img: "images/img-3.jpg",
  },
  {
    id: "oqis",
    name: "Berry Sandwich Loaf",
    price: 4.5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "images/img-4.jpg",
  },
  {
    id: "mdns",
    name: "Butter Cheese Bread",
    price: 6,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "images/img-4.jpg",
  },
  {
    id: "qweo",
    name: "Cheese Cake",
    price: 6.7,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Cake",
    img: "images/img-4.jpg",
  },
  {
    id: "gnms",
    name: "Brown Sugar Bread",
    price: 5.2,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "images/img-4.jpg",
  },
  {
    id: "qwuh",
    name: "Cream Cake",
    price: 1.3,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "images/img-4.jpg",
  },
  {
    id: "ibch",
    name: "Almond Bread Loaf",
    price: 5.4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "images/img-4.jpg",
  },
  {
    id: "jjjm",
    name: "Butter Cake",
    price: 4.5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Cake",
    img: "images/img-4.jpg",
  },
  {
    id: "kisjf",
    name: "Honey Pancake",
    price: 2.1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Cake",
    img: "images/img-4.jpg",
  },
  {
    id: "qqwu",
    name: "Berry Muffin",
    price: 3,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Muffin",
    img: "images/img-4.jpg",
  },
  {
    id: "msad",
    name: "Croissant",
    price: 4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "images/img-4.jpg",
  },
  {
    id: "oran",
    name: "Florence Oval",
    price: 3.2,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "images/img-4.jpg",
  },
  {
    id: "psdaj",
    name: "Original Cookie",
    price: 2.2,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "images/img-4.jpg",
  },
  {
    id: "proSB",
    name: "Snow Bagel",
    price: 3.1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "images/img-4.jpg",
  },
];

