let shopItemsData = [
  {
    id: "abcd",
    name: "Choco Muffin",
    price: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Muffin",
    img: "/Images/Products/1.png",
  },
  {
    id: "xyzh",
    name: "Lava Bread",
    price: 2,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "/Images/Products/2.png",
  },
  {
    id: "ujfh",
    name: "French Bread",
    price: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "/Images/Products/3.png",
  },
  {
    id: "oqis",
    name: "Berry Sandwich Loaf",
    price: 4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "/Images/Products/4.png",
  },
  {
    id: "mdns",
    name: "Butter Cheese Bread",
    price: 6,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "/Images/Products/5.png",
  },
  {
    id: "qweo",
    name: "Cheese Cake",
    price: 6,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Cake",
    img: "/Images/Products/6.png",
  },
  {
    id: "gnms",
    name: "Brown Sugar Bread",
    price: 5.2,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "/Images/Products/7.png",
  },
  {
    id: "qwuh",
    name: "Cream Cake",
    price: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "/Images/Products/8.png",
  },
  {
    id: "ibch",
    name: "Almond Bread Loaf",
    price: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "/Images/Products/9.png",
  },
  {
    id: "jjjm",
    name: "Butter Cake",
    price: 4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Cake",
    img: "/Images/Products/10.png",
  },
  {
    id: "kisjf",
    name: "Honey Pancake",
    price: 2,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Cake",
    img: "/Images/Products/11.png",
  },
  {
    id: "qqwu",
    name: "Berry Muffin",
    price: 3,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Muffin",
    img: "/Images/Products/12.png",
  },
  {
    id: "msad",
    name: "Croissant",
    price: 4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "/Images/Products/13.png",
  },
  {
    id: "oran",
    name: "Florence Oval",
    price: 3,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "/Images/Products/14.png",
  },
  {
    id: "psdaj",
    name: "Original Cookie",
    price: 2,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "/Images/Products/15.png",
  },
  {
    id: "proSB",
    name: "Snow Bagel",
    price: 3,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "Bread",
    img: "/Images/Products/16.png",
  },
];

